apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-no-as-cluster
  region: eu-west-1

managedNodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 2
    minSize: 1
    maxSize: 10
    volumeSize: 20
    privateNetworking: true
    ssh:
      allow: true
      publicKeyName: BasicKeyPair
