apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-redis
  labels:
    deployment: local-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: local-redis
  template:
    metadata:
      labels:
        pod: local-redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        imagePullPolicy: IfNotPresent        
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
